config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :home do
    collection do
      get 'xmas', as: "christmas_event"
      get 'new_year', as: "new_year_event"
      get 'new_event', as: "new_event"
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

  def xmas
    @xmas = Event.find_by(name: "Christmas").date.strftime('%b %d, %Y %H:%M:%S')
  end

  def new_year

  end

  def new_event

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1> Hello World! </h1>

app/views/home/new_event.html.erb
new

app/views/home/new_year.html.erb
<%= javascript_pack_tag 'new_year' %>
<p id="new_year"></p>

app/views/home/xmas.html.erb
<%= javascript_pack_tag 'xmas' %>
<p id="xmas"></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render partial: "navigation menu/nav" %>
      
      
  <%= yield %>
  </body>
</html>

app/views/navigation menu/_nav.html.erb
<nav class = "navbar-callopse">
    <div>
        <ul class = "navbar navopac">
           <li class = "nav-link"> <%= link_to "Christmas #{$year}", christmas_event_home_index_path, class: "nav-item" %></li>
           <li class = "nav-link"> <%= link_to "New Year #{$year}", new_year_event_home_index_path, class: "nav-item"%></li>
           <li class = "nav-link"> <%= link_to "Your event", new_event_home_index_path, class: "nav-item" %></li>
        </ul>
    </div>
</nav>